title: Nic Weber
# brand: Jekyll&Bootstrap
email: nmweber@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  Faculty homepage

baseurl: "/jekyll-bootstrap4-boilerplate" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: ./post/:title

exclude:
  - node_modules
  - README.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
theme: jekyll-theme-cayman

contributorBios:
author: 
    groundh0g:    
      name:       Joseph Hall
      alias:      groundh0g
      image:      images/contributors/groundh0g.png
      role:       author, Programmer / Writer
      bio: > # brief description goes here
        Joe lives with his wife and three daughters in Newnan, Georgia. Every
        summer, Joe teaches high school students how to write games during an
        intense weeklong course in North Carolina for Landry Academy. In his free
        time, Joe dabbles in sketching, cartooning, and creating 3D models. When
        you see his artistic creations, you’ll understand why he makes his living
        as a programmer.
      email:      hello@codetopia.com
      website:    http://codetopia.com/
      twitter:    groundh0g
      facebook:   groundh0g
      youtube:    groundh0g
      instagram:  groundh0g72
      #googleplus: groundh0g
      github:     groundh0g
      deviant:    groundh0g
      linkedin:   groundh0g
      pinterest:  groundh0g
