title: Nic Weber
# brand: Jekyll&Bootstrap
email: nmweber@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  Faculty homepage

baseurl: "/jekyll-bootstrap4-boilerplate" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: ./post/:title

exclude:
  - node_modules
  - README.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
theme: jekyll-theme-cayman
