title: Jekyll Bootstrap 4 + Browserify Boilerplate
brand: Jekyll&Bootstrap
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Starter boilerplate project for Jekyll with Bootstrap 4 and Browserify.

baseurl: "/jekyll-bootstrap4-boilerplate" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: ./post/:title

exclude:
  - node_modules
  - README.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
theme: jekyll-theme-cayman

contributorBios:
    groundh0g:
      name:       Joseph Hall
      alias:      groundh0g
      image:      images/contributors/groundh0g.png
      role:       Programmer / Writer
      bio: > # brief description goes here
        Joe lives with his wife and three daughters in Newnan, Georgia. Every
        summer, Joe teaches high school students how to write games during an
        intense weeklong course in North Carolina for Landry Academy. In his free
        time, Joe dabbles in sketching, cartooning, and creating 3D models. When
        you see his artistic creations, you’ll understand why he makes his living
        as a programmer.
      email:      hello@codetopia.com
      website:    http://codetopia.com/
      twitter:    groundh0g
      facebook:   groundh0g
      youtube:    groundh0g
      instagram:  groundh0g72
      #googleplus: groundh0g
      github:     groundh0g
      deviant:    groundh0g
      linkedin:   groundh0g
      pinterest:  groundh0g
    plusjade:
      name:       Jade Dominguez
      alias:      plusjade
      image:      images/contributors/plusjade.jpg
      role:       Programmer
      bio: > # brief description goes here
        I owe everything I know to the Open Source community so all my work is
        Open and Free. My most popular project and claim to baby fame is
        JekyllBootstrap which ironically has the least amount of actual code than
        any of my other projects; a testament to the importance of being user and
        usability driven.
      email:      plusjade@gmail.com
      website:    http://plusjade.com/
      twitter:    plusjade
      github:     plusjade
    # FIXME: actually use admin alias as default in posts (and pages?)
    admin:        # the "admin" author alias is reserved, used as default when no author is specified
      name:       Administrator
      alias:      admin
      showInList: true # you can hide this little guy
      image:      images/contributors/admin.png
      role:       Filth-Dimensional Being
      bio: > # brief description goes here
        The "admin" alias is a reserved account, used as default when no author is specified.<br/>
        You can hide this account by adding "showInList: false" to the "_config.yml" file.
      email:      hello@jaytch.org
      website:    http://jaytch.org/
      twitter:    GetJaytch

  analytics : # settings for analytics, set 'provider' to the analytics provider you want to use
    provider : google # Set 'provider' to false to turn analytics off entirely
    gauges :
        site_id : 'SITE ID'
    google :
        tracking_id : 'UA-123-12'
    googleLegacy :
        tracking_id : 'UA-123-12'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    baidu :
        token : '_BAIDU_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik

  comments : # settings for comments helper, set 'provider' to the comment provider you want to use
    provider : facebook # Set 'provider' to false to turn commenting off entirely
    disqus :
      short_name : myname
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
    duoshuo :
      short_name : myname
